import bmesh


def _prepare_indices(bm: bmesh.types.BMesh) -> None:
    """Keep BMesh indices deterministic and aligned with exported OBJ order."""
    bm.verts.index_update()
    bm.edges.index_update()
    bm.faces.index_update()
    bm.verts.ensure_lookup_table()
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()
    bm.normal_update()


def export_sharp_features(bm: bmesh.types.BMesh, sharp_filepath: str, sharp_angle: float = 35) -> int:
    """Export marked sharp/boundary/seam edges in QuadWild's feature format.

    Face indices must match the OBJ face order exactly. In the previous code,
    triangulation could leave stale BMesh face indices, causing feature edges to
    be attached to the wrong triangles and producing seemingly random flow.
    """
    del sharp_angle  # Kept for API compatibility.
    _prepare_indices(bm)

    sharp_edges = []
    for edge in bm.edges:
        if edge.is_wire or edge.smooth or not edge.link_faces:
            continue

        convexity = 1 if edge.is_convex else 0
        face = edge.link_faces[0]

        edge_index = None
        for loop_index, loop in enumerate(face.loops):
            if loop.edge == edge:
                edge_index = loop_index
                break

        if edge_index is None:
            continue

        sharp_edges.append(f"{convexity},{face.index},{edge_index}")

    with open(sharp_filepath, "w", encoding="utf-8", newline="\n") as file:
        file.write(f"{len(sharp_edges)}\n")
        for edge in sharp_edges:
            file.write(f"{edge}\n")

    return len(sharp_edges)


def export_mesh(bm: bmesh.types.BMesh, mesh_filepath: str) -> None:
    """Export mesh as the minimal OBJ subset consumed by QuadWild."""
    _prepare_indices(bm)

    verts = [f"v {v.co.x:.9f} {v.co.y:.9f} {v.co.z:.9f}" for v in bm.verts]
    vert_normals = []
    faces = []

    for face_index, face in enumerate(bm.faces):
        vert_normals.append(f"vn {face.normal.x:.7f} {face.normal.y:.7f} {face.normal.z:.7f}")
        face_verts = [f"{vert.index + 1}//{face_index + 1}" for vert in face.verts]
        faces.append(f"f {' '.join(face_verts)}")

    with open(mesh_filepath, "w", encoding="utf-8", newline="\n") as file:
        file.write("# OBJ file generated by QRemeshify\n")
        file.write("\n".join(verts))
        file.write("\n")
        file.write("\n".join(vert_normals))
        file.write("\n")
        file.write("\n".join(faces))
        file.write("\n")
